class_name STAT
extends Node

enum STATUS_ENUM {
	REGEN_STATUS,
	ATTACK_SCALING_STATUS,
	ARMOR_FROM_DAMAGE_STATUS,
	DOT_STATUS,
	VAMPIRE_STATUS,
	XP_STATUS,
	DAMAGE_MULTIPLIER_STATUS,
	BUFF_DOOR_HEALING_STATUS,
	FURY_STATUS,
	POISONER_STATUS,
	}

var STATUS: Dictionary[STATUS_ENUM, Callable] = {
	STATUS_ENUM.REGEN_STATUS : RegenStatus.new,
	STATUS_ENUM.ATTACK_SCALING_STATUS : AttackScalingStatus.new,
	STATUS_ENUM.ARMOR_FROM_DAMAGE_STATUS : ArmorFromDamageStatus.new,
	STATUS_ENUM.DOT_STATUS : DamageOverTimeStatus.new,
	STATUS_ENUM.VAMPIRE_STATUS : VampireStatus.new,
	STATUS_ENUM.XP_STATUS : XPStatus.new,
	STATUS_ENUM.DAMAGE_MULTIPLIER_STATUS : DamageMultiplierStatus.new,
	STATUS_ENUM.BUFF_DOOR_HEALING_STATUS : BuffDoorHealingStatus.new,
	STATUS_ENUM.FURY_STATUS : FuryStatus.new,
	STATUS_ENUM.POISONER_STATUS : PoisonerStatus.new,
	}
